/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.pds16.pds16asm;

import org.pds16.pds16asm.Pds16asmStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Pds16asmStandaloneSetup extends Pds16asmStandaloneSetupGenerated {
  public static void doSetup() {
    Pds16asmStandaloneSetup _pds16asmStandaloneSetup = new Pds16asmStandaloneSetup();
    _pds16asmStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
