/*
 * generated by Xtext 2.10.1
 */
package org.pds16.pds16asm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPds16asmScopeProvider extends DelegatingScopeProvider {
}
