/**
 * generated by Xtext 2.9.2
 */
package org.pds16.pds16asm.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.pds16.pds16asm.HexaDecimal;
import org.pds16.pds16asm.Indexed;
import org.pds16.pds16asm.Pds16asmPackage;
import org.pds16.pds16asm.Registers;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Indexed</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.pds16.pds16asm.impl.IndexedImpl#getReg <em>Reg</em>}</li>
 *   <li>{@link org.pds16.pds16asm.impl.IndexedImpl#getImediate8 <em>Imediate8</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class IndexedImpl extends MinimalEObjectImpl.Container implements Indexed
{
  /**
   * The cached value of the '{@link #getReg() <em>Reg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReg()
   * @generated
   * @ordered
   */
  protected Registers reg;

  /**
   * The cached value of the '{@link #getImediate8() <em>Imediate8</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImediate8()
   * @generated
   * @ordered
   */
  protected HexaDecimal imediate8;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IndexedImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pds16asmPackage.Literals.INDEXED;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Registers getReg()
  {
    return reg;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReg(Registers newReg, NotificationChain msgs)
  {
    Registers oldReg = reg;
    reg = newReg;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pds16asmPackage.INDEXED__REG, oldReg, newReg);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReg(Registers newReg)
  {
    if (newReg != reg)
    {
      NotificationChain msgs = null;
      if (reg != null)
        msgs = ((InternalEObject)reg).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Pds16asmPackage.INDEXED__REG, null, msgs);
      if (newReg != null)
        msgs = ((InternalEObject)newReg).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Pds16asmPackage.INDEXED__REG, null, msgs);
      msgs = basicSetReg(newReg, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pds16asmPackage.INDEXED__REG, newReg, newReg));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HexaDecimal getImediate8()
  {
    return imediate8;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetImediate8(HexaDecimal newImediate8, NotificationChain msgs)
  {
    HexaDecimal oldImediate8 = imediate8;
    imediate8 = newImediate8;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Pds16asmPackage.INDEXED__IMEDIATE8, oldImediate8, newImediate8);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setImediate8(HexaDecimal newImediate8)
  {
    if (newImediate8 != imediate8)
    {
      NotificationChain msgs = null;
      if (imediate8 != null)
        msgs = ((InternalEObject)imediate8).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Pds16asmPackage.INDEXED__IMEDIATE8, null, msgs);
      if (newImediate8 != null)
        msgs = ((InternalEObject)newImediate8).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Pds16asmPackage.INDEXED__IMEDIATE8, null, msgs);
      msgs = basicSetImediate8(newImediate8, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Pds16asmPackage.INDEXED__IMEDIATE8, newImediate8, newImediate8));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Pds16asmPackage.INDEXED__REG:
        return basicSetReg(null, msgs);
      case Pds16asmPackage.INDEXED__IMEDIATE8:
        return basicSetImediate8(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Pds16asmPackage.INDEXED__REG:
        return getReg();
      case Pds16asmPackage.INDEXED__IMEDIATE8:
        return getImediate8();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Pds16asmPackage.INDEXED__REG:
        setReg((Registers)newValue);
        return;
      case Pds16asmPackage.INDEXED__IMEDIATE8:
        setImediate8((HexaDecimal)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Pds16asmPackage.INDEXED__REG:
        setReg((Registers)null);
        return;
      case Pds16asmPackage.INDEXED__IMEDIATE8:
        setImediate8((HexaDecimal)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Pds16asmPackage.INDEXED__REG:
        return reg != null;
      case Pds16asmPackage.INDEXED__IMEDIATE8:
        return imediate8 != null;
    }
    return super.eIsSet(featureID);
  }

} //IndexedImpl
