/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.pds16.pds16asm.pds16asm.impl;

import org.eclipse.emf.ecore.EClass;

import org.pds16.pds16asm.pds16asm.Pds16asmPackage;
import org.pds16.pds16asm.pds16asm.Rr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RrImpl extends LogicaImpl implements Rr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RrImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pds16asmPackage.Literals.RR;
  }

} //RrImpl
