/**
 * generated by Xtext 2.10.1
 */
package org.pds16.pds16asm.pds16asm.impl;

import org.eclipse.emf.ecore.EClass;

import org.pds16.pds16asm.pds16asm.Pds16asmPackage;
import org.pds16.pds16asm.pds16asm.Sub;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sub</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SubImpl extends AritmeticaImpl implements Sub
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pds16asmPackage.Literals.SUB;
  }

} //SubImpl
