/**
 * generated by Xtext 2.10.0
 */
package org.pds16.pds16asm.pds16asm.impl;

import org.eclipse.emf.ecore.EClass;

import org.pds16.pds16asm.pds16asm.Pds16asmPackage;
import org.pds16.pds16asm.pds16asm.Xrl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Xrl</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class XrlImpl extends LogicaImpl implements Xrl
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XrlImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Pds16asmPackage.Literals.XRL;
  }

} //XrlImpl
