/**
 * generated by Xtext 2.10.1
 */
package org.pds16.pds16asm.pds16asm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rc</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.pds16.pds16asm.pds16asm.Pds16asmPackage#getRc()
 * @model
 * @generated
 */
public interface Rc extends Logica
{
} // Rc
