/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.pds16.pds16asm.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.pds16.pds16asm.pds16asm.Equ;
import org.pds16.pds16asm.pds16asm.Label;
import org.pds16.pds16asm.pds16asm.Org;
import org.pds16.pds16asm.pds16asm.Section;
import org.pds16.pds16asm.pds16asm.Set;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class Pds16asmLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public Pds16asmLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final Label l) {
    String _labelName = l.getLabelName();
    String _labelName_1 = l.getLabelName();
    int _length = _labelName_1.length();
    int _minus = (_length - 1);
    String _substring = _labelName.substring(0, _minus);
    return ("Label: " + _substring);
  }
  
  public String text(final Equ ele) {
    String _id = ele.getId();
    return ("Equ: " + _id);
  }
  
  public String text(final Org ele) {
    return "Org ";
  }
  
  public String text(final Section ele) {
    String _id = ele.getId();
    return ("Section: " + _id);
  }
  
  public String text(final Set ele) {
    String _id = ele.getId();
    return ("Set: " + _id);
  }
}
