/**
 * generated by Xtext 2.9.2
 */
package org.pds16.pds16asm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ld Immediate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.pds16.pds16asm.Pds16asmPackage#getLdImmediate()
 * @model
 * @generated
 */
public interface LdImmediate extends Load
{
} // LdImmediate
