/**
 * generated by Xtext 2.9.2
 */
package org.pds16.pds16asm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>operation Shift</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.pds16.pds16asm.operationShift#getRd <em>Rd</em>}</li>
 *   <li>{@link org.pds16.pds16asm.operationShift#getRm <em>Rm</em>}</li>
 *   <li>{@link org.pds16.pds16asm.operationShift#getConst4 <em>Const4</em>}</li>
 *   <li>{@link org.pds16.pds16asm.operationShift#getSin <em>Sin</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.pds16.pds16asm.Pds16asmPackage#getoperationShift()
 * @model
 * @generated
 */
public interface operationShift extends SHL, SHR
{
  /**
   * Returns the value of the '<em><b>Rd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rd</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rd</em>' containment reference.
   * @see #setRd(Registers)
   * @see org.pds16.pds16asm.Pds16asmPackage#getoperationShift_Rd()
   * @model containment="true"
   * @generated
   */
  Registers getRd();

  /**
   * Sets the value of the '{@link org.pds16.pds16asm.operationShift#getRd <em>Rd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rd</em>' containment reference.
   * @see #getRd()
   * @generated
   */
  void setRd(Registers value);

  /**
   * Returns the value of the '<em><b>Rm</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rm</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rm</em>' containment reference.
   * @see #setRm(Registers)
   * @see org.pds16.pds16asm.Pds16asmPackage#getoperationShift_Rm()
   * @model containment="true"
   * @generated
   */
  Registers getRm();

  /**
   * Sets the value of the '{@link org.pds16.pds16asm.operationShift#getRm <em>Rm</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rm</em>' containment reference.
   * @see #getRm()
   * @generated
   */
  void setRm(Registers value);

  /**
   * Returns the value of the '<em><b>Const4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Const4</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const4</em>' attribute.
   * @see #setConst4(int)
   * @see org.pds16.pds16asm.Pds16asmPackage#getoperationShift_Const4()
   * @model
   * @generated
   */
  int getConst4();

  /**
   * Sets the value of the '{@link org.pds16.pds16asm.operationShift#getConst4 <em>Const4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const4</em>' attribute.
   * @see #getConst4()
   * @generated
   */
  void setConst4(int value);

  /**
   * Returns the value of the '<em><b>Sin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sin</em>' attribute.
   * @see #setSin(int)
   * @see org.pds16.pds16asm.Pds16asmPackage#getoperationShift_Sin()
   * @model
   * @generated
   */
  int getSin();

  /**
   * Sets the value of the '{@link org.pds16.pds16asm.operationShift#getSin <em>Sin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sin</em>' attribute.
   * @see #getSin()
   * @generated
   */
  void setSin(int value);

} // operationShift
