/**
 * generated by Xtext 2.9.2
 */
package org.pds16.pds16asm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation LDI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.pds16.pds16asm.OperationLDI#getImmediate8 <em>Immediate8</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.pds16.pds16asm.Pds16asmPackage#getOperationLDI()
 * @model
 * @generated
 */
public interface OperationLDI extends Operations
{
  /**
   * Returns the value of the '<em><b>Immediate8</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Immediate8</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Immediate8</em>' containment reference.
   * @see #setImmediate8(HexaDecimal)
   * @see org.pds16.pds16asm.Pds16asmPackage#getOperationLDI_Immediate8()
   * @model containment="true"
   * @generated
   */
  HexaDecimal getImmediate8();

  /**
   * Sets the value of the '{@link org.pds16.pds16asm.OperationLDI#getImmediate8 <em>Immediate8</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Immediate8</em>' containment reference.
   * @see #getImmediate8()
   * @generated
   */
  void setImmediate8(HexaDecimal value);

} // OperationLDI
