/**
 * generated by Xtext 2.9.2
 */
package org.pds16.pds16asm;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.pds16.pds16asm.Pds16asmPackage
 * @generated
 */
public interface Pds16asmFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Pds16asmFactory eINSTANCE = org.pds16.pds16asm.impl.Pds16asmFactoryImpl.init();

  /**
   * Returns a new object of class '<em>PDS16ASM</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PDS16ASM</em>'.
   * @generated
   */
  PDS16ASM createPDS16ASM();

  /**
   * Returns a new object of class '<em>Instructions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instructions</em>'.
   * @generated
   */
  Instructions createInstructions();

  /**
   * Returns a new object of class '<em>Load</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load</em>'.
   * @generated
   */
  Load createLoad();

  /**
   * Returns a new object of class '<em>Store</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Store</em>'.
   * @generated
   */
  Store createStore();

  /**
   * Returns a new object of class '<em>Aritmetica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Aritmetica</em>'.
   * @generated
   */
  Aritmetica createAritmetica();

  /**
   * Returns a new object of class '<em>Logica</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Logica</em>'.
   * @generated
   */
  Logica createLogica();

  /**
   * Returns a new object of class '<em>Jump</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Jump</em>'.
   * @generated
   */
  Jump createJump();

  /**
   * Returns a new object of class '<em>Ld Immediate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ld Immediate</em>'.
   * @generated
   */
  LdImmediate createLdImmediate();

  /**
   * Returns a new object of class '<em>Ld Direct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ld Direct</em>'.
   * @generated
   */
  LdDirect createLdDirect();

  /**
   * Returns a new object of class '<em>Ld Indexed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ld Indexed</em>'.
   * @generated
   */
  LdIndexed createLdIndexed();

  /**
   * Returns a new object of class '<em>Ld Based Indexed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ld Based Indexed</em>'.
   * @generated
   */
  LdBasedIndexed createLdBasedIndexed();

  /**
   * Returns a new object of class '<em>St Direct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>St Direct</em>'.
   * @generated
   */
  StDirect createStDirect();

  /**
   * Returns a new object of class '<em>St Indexed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>St Indexed</em>'.
   * @generated
   */
  StIndexed createStIndexed();

  /**
   * Returns a new object of class '<em>St Based Indexed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>St Based Indexed</em>'.
   * @generated
   */
  StBasedIndexed createStBasedIndexed();

  /**
   * Returns a new object of class '<em>Add Registers</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Registers</em>'.
   * @generated
   */
  AddRegisters createAddRegisters();

  /**
   * Returns a new object of class '<em>Add Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Constant</em>'.
   * @generated
   */
  AddConstant createAddConstant();

  /**
   * Returns a new object of class '<em>Sub Registers</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Registers</em>'.
   * @generated
   */
  SubRegisters createSubRegisters();

  /**
   * Returns a new object of class '<em>Sub Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sub Constant</em>'.
   * @generated
   */
  SubConstant createSubConstant();

  /**
   * Returns a new object of class '<em>ANL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ANL</em>'.
   * @generated
   */
  ANL createANL();

  /**
   * Returns a new object of class '<em>ORL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ORL</em>'.
   * @generated
   */
  ORL createORL();

  /**
   * Returns a new object of class '<em>XRL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XRL</em>'.
   * @generated
   */
  XRL createXRL();

  /**
   * Returns a new object of class '<em>NOT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NOT</em>'.
   * @generated
   */
  NOT createNOT();

  /**
   * Returns a new object of class '<em>SHL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SHL</em>'.
   * @generated
   */
  SHL createSHL();

  /**
   * Returns a new object of class '<em>SHR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SHR</em>'.
   * @generated
   */
  SHR createSHR();

  /**
   * Returns a new object of class '<em>RR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RR</em>'.
   * @generated
   */
  RR createRR();

  /**
   * Returns a new object of class '<em>RC</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RC</em>'.
   * @generated
   */
  RC createRC();

  /**
   * Returns a new object of class '<em>Jump Op</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Jump Op</em>'.
   * @generated
   */
  JumpOp createJumpOp();

  /**
   * Returns a new object of class '<em>Immediate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Immediate</em>'.
   * @generated
   */
  Immediate createImmediate();

  /**
   * Returns a new object of class '<em>Direct</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Direct</em>'.
   * @generated
   */
  Direct createDirect();

  /**
   * Returns a new object of class '<em>Indexed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Indexed</em>'.
   * @generated
   */
  Indexed createIndexed();

  /**
   * Returns a new object of class '<em>Based Indexed</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Based Indexed</em>'.
   * @generated
   */
  BasedIndexed createBasedIndexed();

  /**
   * Returns a new object of class '<em>Hexa Decimal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hexa Decimal</em>'.
   * @generated
   */
  HexaDecimal createHexaDecimal();

  /**
   * Returns a new object of class '<em>operation With Two Registers</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>operation With Two Registers</em>'.
   * @generated
   */
  operationWithTwoRegisters createoperationWithTwoRegisters();

  /**
   * Returns a new object of class '<em>operations With Tree Registers</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>operations With Tree Registers</em>'.
   * @generated
   */
  operationsWithTreeRegisters createoperationsWithTreeRegisters();

  /**
   * Returns a new object of class '<em>operations With Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>operations With Constant</em>'.
   * @generated
   */
  operationsWithConstant createoperationsWithConstant();

  /**
   * Returns a new object of class '<em>operation Shift</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>operation Shift</em>'.
   * @generated
   */
  operationShift createoperationShift();

  /**
   * Returns a new object of class '<em>operation With Offset</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>operation With Offset</em>'.
   * @generated
   */
  operationWithOffset createoperationWithOffset();

  /**
   * Returns a new object of class '<em>Comment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comment</em>'.
   * @generated
   */
  Comment createComment();

  /**
   * Returns a new object of class '<em>Registers</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Registers</em>'.
   * @generated
   */
  Registers createRegisters();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  Pds16asmPackage getPds16asmPackage();

} //Pds16asmFactory
