/*
 * generated by Xtext 2.10.0
 */
package org.pds16.pds16asm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.pds16.pds16asm.ui.internal.Pds16asmActivator;

public class Pds16asmUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Pds16asmActivator.getInstance().getInjector("org.pds16.pds16asm.Pds16asm");
	}

}
