/**
 * generated by Xtext 2.9.2
 */
package org.pds16.pds16asm.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.pds16.pds16asm.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.pds16.pds16asm.Pds16asmPackage
 * @generated
 */
public class Pds16asmSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static Pds16asmPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Pds16asmSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = Pds16asmPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @parameter ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case Pds16asmPackage.PDS16ASM:
      {
        PDS16ASM pds16ASM = (PDS16ASM)theEObject;
        T result = casePDS16ASM(pds16ASM);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.INSTRUCTIONS:
      {
        Instructions instructions = (Instructions)theEObject;
        T result = caseInstructions(instructions);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.LOAD:
      {
        Load load = (Load)theEObject;
        T result = caseLoad(load);
        if (result == null) result = caseInstructions(load);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.LD_IMMEDIATE:
      {
        LdImmediate ldImmediate = (LdImmediate)theEObject;
        T result = caseLdImmediate(ldImmediate);
        if (result == null) result = caseLoad(ldImmediate);
        if (result == null) result = caseInstructions(ldImmediate);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.LD_DIRECT:
      {
        LdDirect ldDirect = (LdDirect)theEObject;
        T result = caseLdDirect(ldDirect);
        if (result == null) result = caseLoad(ldDirect);
        if (result == null) result = caseInstructions(ldDirect);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.LD_INDEXED:
      {
        LdIndexed ldIndexed = (LdIndexed)theEObject;
        T result = caseLdIndexed(ldIndexed);
        if (result == null) result = caseLoad(ldIndexed);
        if (result == null) result = caseInstructions(ldIndexed);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.LD_BASED_INDEXED:
      {
        LdBasedIndexed ldBasedIndexed = (LdBasedIndexed)theEObject;
        T result = caseLdBasedIndexed(ldBasedIndexed);
        if (result == null) result = caseLoad(ldBasedIndexed);
        if (result == null) result = caseInstructions(ldBasedIndexed);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.IMMEDIATE:
      {
        Immediate immediate = (Immediate)theEObject;
        T result = caseImmediate(immediate);
        if (result == null) result = caseLdImmediate(immediate);
        if (result == null) result = caseLoad(immediate);
        if (result == null) result = caseInstructions(immediate);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.DIRECT:
      {
        Direct direct = (Direct)theEObject;
        T result = caseDirect(direct);
        if (result == null) result = caseLdDirect(direct);
        if (result == null) result = caseLoad(direct);
        if (result == null) result = caseInstructions(direct);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.INDEXED:
      {
        Indexed indexed = (Indexed)theEObject;
        T result = caseIndexed(indexed);
        if (result == null) result = caseLdIndexed(indexed);
        if (result == null) result = caseLoad(indexed);
        if (result == null) result = caseInstructions(indexed);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.BASED_INDEXED:
      {
        BasedIndexed basedIndexed = (BasedIndexed)theEObject;
        T result = caseBasedIndexed(basedIndexed);
        if (result == null) result = caseLdBasedIndexed(basedIndexed);
        if (result == null) result = caseLoad(basedIndexed);
        if (result == null) result = caseInstructions(basedIndexed);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.HEXA_DECIMAL:
      {
        HexaDecimal hexaDecimal = (HexaDecimal)theEObject;
        T result = caseHexaDecimal(hexaDecimal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.COMMENT:
      {
        Comment comment = (Comment)theEObject;
        T result = caseComment(comment);
        if (result == null) result = caseInstructions(comment);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Pds16asmPackage.REGISTERS:
      {
        Registers registers = (Registers)theEObject;
        T result = caseRegisters(registers);
        if (result == null) result = caseBasedIndexed(registers);
        if (result == null) result = caseLdBasedIndexed(registers);
        if (result == null) result = caseLoad(registers);
        if (result == null) result = caseInstructions(registers);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>PDS16ASM</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>PDS16ASM</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePDS16ASM(PDS16ASM object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Instructions</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Instructions</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInstructions(Instructions object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Load</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Load</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLoad(Load object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ld Immediate</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ld Immediate</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLdImmediate(LdImmediate object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ld Direct</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ld Direct</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLdDirect(LdDirect object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ld Indexed</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ld Indexed</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLdIndexed(LdIndexed object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ld Based Indexed</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ld Based Indexed</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseLdBasedIndexed(LdBasedIndexed object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Immediate</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Immediate</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseImmediate(Immediate object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Direct</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Direct</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDirect(Direct object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Indexed</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Indexed</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIndexed(Indexed object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Based Indexed</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Based Indexed</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBasedIndexed(BasedIndexed object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Hexa Decimal</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Hexa Decimal</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseHexaDecimal(HexaDecimal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Comment</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Comment</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComment(Comment object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Registers</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Registers</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRegisters(Registers object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //Pds16asmSwitch
